#!/bin/bash
# Install python2 script, pip, pymongo

sudo apt install python

sudo apt install python-pip

pip install pymongo

pip install --upgrade pymongo

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4

echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list

sudo apt-get update

sudo apt-get install -y mongodb-org

mongo --ssl --host docdb-2019-01-13-20-41-26.cluster-cealhvkvnunf.us-east-2.docdb.amazonaws.com:27017 --sslCAFile rds-combined-ca-bundle.pem --username docuDB --password Physics26
